export const CREATE_DECK = 'CREATE_DECK';
export const DELETE_DECK = 'DELETE_DECK';
export const REVIEW_DECK = 'REVIEW_DECK';
export const DELETE_ALL_DECKS = 'DELETE_ALL_DECKS';
export const FETCH_DECKS = 'FETCH_DECKS';
export const FETCH_DECKS_PENDING = 'FETCH_DECKS_PENDING';
export const FETCH_DECKS_FULFILLED = 'FETCH_DECKS_FULFILLED';
export const FETCH_DECKS_REJECTED = 'FETCH_DECKS_REJECTED';